obj-m += ipts.o

ipts-objs := cmd.o
ipts-objs += control.o
ipts-objs += eds1.o
ipts-objs += eds2.o
ipts-objs += hid.o
ipts-objs += main.o
ipts-objs += mei.o
ipts-objs += receiver.o
ipts-objs += resources.o
ipts-objs += thread.o
